# Generated by Django 5.1.6 on 2025-04-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "text",
                    models.TextField(max_length=1500, verbose_name="Текст письма"),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="SendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fio", models.CharField(blank=True, null=True)),
                ("description", models.CharField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Sending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_first", models.DateField(verbose_name="Дата начала")),
                ("date_last", models.DateField(verbose_name="Дата окончания")),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                (
                    "mail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sendings",
                        to="sending_emeil.email",
                        verbose_name="Письмо",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mailings",
                        to="sending_emeil.sendinguser",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["mail"],
            },
        ),
    ]
