# Generated by Django 5.1.6 on 2025-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sendinguser",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
