# Generated by Django 5.1.6 on 2025-04-08 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sending",
            name="mail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Письма",
                to="sending_emeil.email",
                verbose_name="Письма",
            ),
        ),
        migrations.AlterField(
            model_name="sending",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="Получатели",
                to="sending_emeil.sendinguser",
                verbose_name="Получатели",
            ),
        ),
    ]
