# Generated by Django 5.1.6 on 2025-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0002_alter_sending_mail_alter_sending_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sending",
            name="date_first",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="sending",
            name="date_last",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="sending",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
