# Generated by Django 5.1.6 on 2025-04-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sending_emeil",
            "0003_alter_sending_date_first_alter_sending_date_last_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendinguser",
            options={
                "ordering": ["email"],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
