# Generated by Django 5.1.6 on 2025-04-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0004_alter_sendinguser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sending",
            options={
                "ordering": ["mail"],
                "permissions": [("can_unpublish_sending", "can unpublish sending")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="sending",
            name="mail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Письма",
                to="sending_emeil.email",
            ),
        ),
        migrations.AlterField(
            model_name="sending",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="Получатели", to="sending_emeil.sendinguser"
            ),
        ),
        migrations.CreateModel(
            name="SendTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "успешная рассылка"),
                            ("fail", "рассылка провалилась"),
                            ("on_stop", "приостановлена (не запущена)"),
                            ("canceled", "прекращена"),
                        ],
                        default="on_stop",
                        null=True,
                    ),
                ),
                ("date_of_try", models.DateField(auto_now=True)),
                ("answer_server", models.TextField(blank=True, null=True)),
                (
                    "sending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sending_emeil.sending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["status"],
            },
        ),
    ]
