# Generated by Django 5.1.6 on 2025-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0006_alter_sending_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sending",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                verbose_name="Статус",
            ),
        ),
    ]
