# Generated by Django 5.1.6 on 2025-04-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_emeil", "0007_alter_sending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sending",
            name="is_publish",
            field=models.BooleanField(default=True, verbose_name="Можно запустить"),
        ),
        migrations.AlterField(
            model_name="sending",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("stoped", "Остановлена менеджером"),
                ],
                default="created",
                verbose_name="Статус",
            ),
        ),
    ]
