# Generated by Django 5.1.6 on 2025-04-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth",
            name="code",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="auth",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
