# Generated by Django 5.1.6 on 2025-04-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="code",
            old_name="email_address",
            new_name="user",
        ),
    ]
