# Generated by Django 5.1.6 on 2025-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_rename_email_address_code_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
