# Generated by Django 5.1.6 on 2025-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_auth_code_alter_auth_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth",
            name="is_auth",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
