# Generated by Django 5.1.6 on 2025-04-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_auth_is_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
