# Generated by Django 5.1.6 on 2025-04-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_alter_auth_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="username",
            field=models.CharField(verbose_name="Имя пользователя"),
        ),
    ]
