# Generated by Django 5.1.6 on 2025-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_alter_auth_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
