# Generated by Django 5.1.6 on 2025-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_alter_auth_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.IntegerField(help_text="Код из сообщения", max_length=4),
                ),
            ],
            options={
                "verbose_name": "код подтверждения",
                "verbose_name_plural": "коды подтверждения",
                "ordering": ["code"],
            },
        ),
    ]
