# Generated by Django 5.1.6 on 2025-04-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_alter_code_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="is_auth",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="code",
            name="code",
            field=models.CharField(help_text="Код из сообщения", unique=True),
        ),
    ]
